---
title: "Police EDA"
author: Connie Wu
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(tidyverse)
library(reshape2)
```

## Load Data

```{r load-data}
# Census Predictors
census <- read.csv("data/2013census.csv")[,-c(8,9)]
states <- lapply(census$department, function(x) str_extract_all(x,"\\([^()]+\\)")[[1]])
states <- substring(states, 2, nchar(states)-1)
census$state <- states

# Gun Law Predictors
gun_provisions <- read.csv("data/gun_provisions.csv") %>% 
  filter(year == 2013)
gun_provisions <- gun_provisions %>% 
  mutate(total_pr = rowSums(gun_provisions[,3:136]),
         deesc_train = ifelse(state %in% c("California", "New Mexico", "Texas", "Oklahoma", "South Dakota", "Illinois", "Indiana", "Tennessee", "Washington", "Missouri", "Georgia", "Ohio", "Maryland", "Massachusetts", "Connecticut", "Maine"), 1, 0)) %>% 
  select(state, total_pr, deesc_train)
gun_provisions$state <- state.abb[match(gun_provisions$state,state.name)]
```

### Clean all

```{r clean-all}
all <- read.csv("data/allshootingsdata.csv")

# Recode subject race
all$SubjectRace[is.na(all$SubjectRace)] <- "A"

# Recode officer races
all$OfficerRace <- gsub("H/L", "L", all$OfficerRace)
all$OfficerRace <- gsub("H", "L", all$OfficerRace)
all$OfficerRace <- gsub("Unknown|m/m", "U", all$OfficerRace)
all$OfficerRace <- gsub("WHITE|WLITE", "W", all$OfficerRace)
all$OfficerRace <- gsub("BLACK", "B", all$OfficerRace)
all$OfficerRace <- gsub("ASIAN", "A", all$OfficerRace)
all$OfficerRace <- gsub("Other|AI/AN|NA/W|Multi-Racial", "O", all$OfficerRace)
all$OfficerRace <- gsub("NA", "O", all$OfficerRace)
all$OfficerRace <- gsub("A/PI ", "A;", all$OfficerRace)
all$OfficerRace <- gsub("A/PI", "A", all$OfficerRace)
all$OfficerRace <- gsub(",", ";", all$OfficerRace)
all$OfficerRace <- gsub(" ", "", all$OfficerRace)
all$OfficerRace <- gsub("A/W|W/L|W/A", "O", all$OfficerRace)
all$OfficerRace[all$OfficerRace == ""] <- "U"

# Recode officer genders
all$OfficerGender <- gsub("MALE", "M", toupper(all$OfficerGender))
all$OfficerGender <- gsub("FEMALE|FEM", "F", toupper(all$OfficerGender))
all$OfficerGender <- gsub("UNKNOWN|FALSE", "U", toupper(all$OfficerGender))
all$OfficerGender <- gsub(",|:", ";", toupper(all$OfficerGender))
all$OfficerGender <- gsub(" |/", "", toupper(all$OfficerGender))

all$SubjectArmed[which(is.na(all$SubjectArmed))] <- "U"

numofficerna <- which(is.na(all$NumberOfOfficers))
replacement <- str_count(all$OfficerRace[numofficerna], ";")
replacement <- replacement + 1
all$NumberOfOfficers[numofficerna] <- replacement

all <- all %>% 
  select(-c("Date", "NatureOfStop", "Notes", "SubjectAge", "NumberOfShots", "Department", "FullNarrative", "fdate", "month", "day", "tr", "AvgAge", "VA", "F", "nshots", "sit")) %>% 
  mutate(b = as.numeric(b > 0),
         w = as.numeric(w > 0),
         l = as.numeric(l > 0),
         a = as.numeric(a > 0),
         so =  as.numeric(str_count(all$SubjectRace, "O") > 0),
         smale = as.numeric(str_count(all$SubjectGender, "M") > 0),
         sfem = as.numeric(str_count(all$SubjectGender, "F") > 0),
         ob = as.numeric(str_count(all$OfficerRace, "B") > 0),
         ow = as.numeric(str_count(all$OfficerRace, "W") > 0),
         ol = as.numeric(str_count(all$OfficerRace, "L") > 0),
         oa = as.numeric(str_count(all$OfficerRace, "A") > 0),
         oo =  as.numeric(str_count(all$OfficerRace, "O") > 0),
         omale = as.numeric(str_count(all$OfficerGender, "M") > 0),
         ofem = as.numeric(str_count(all$OfficerGender, "F") > 0),
         omult = as.numeric(all$NumberOfOfficers != "1"),
         other = as.numeric(weapon == "other"), 
         replica = as.numeric(weapon == "replica"), 
         knife = as.numeric(weapon == "knife"), 
         gun = as.numeric(weapon == "gun"), 
         unarmed = as.numeric(weapon == "unarmed"),
         unknown_weapon = as.numeric(weapon == "U"),
         fatal = as.numeric(str_count(all$Fatal, "F") > 0)) %>% 
  select(-c(weapon))

all <- rename(all, sb = b, sw = w, sl = l, sa = a, weapon_other = other)
```

```{r filter-all}
# Filter out unknown values
all <- all[-which(all$smale == 0 & all$sfem == 0),]
all <- all[-which(all$omale == 0 & all$ofem == 0),]
all <- all[-which(all$sb == 0 & all$sw == 0 & all$sl == 0 & all$sa == 0 & all$so == 0),]
all <- all[-which(is.na(all$sb)),]
all <- all[-which(all$ob == 0 & all$ow == 0 & all$ol == 0 & all$oa == 0 & all$oo == 0),]
all <- all[-which(str_count(all$Fatal, "F") == 0 & str_count(all$Fatal, "N") == 0),]
all <- all %>% 
  select(-c(Fatal))
```

```{r merge-data}
final_df <- merge(all, census, by.x = "city", by.y = "city_name")
final_df <- merge(final_df, gun_provisions, by = "state")
final_df <- final_df %>% 
  select(-c(department, year))
final_df$NumberOfSubjects[which(final_df$NumberOfSubjects == 0)] <- 1
final_df$NumberOfOfficers[which(final_df$NumberOfOfficers == "U")] <- 1
```

```{r save-final-df}
saveRDS(final_df, "data/final.rds")
```

## Exploratory Data Analysis 

```{r rename 0 and 1 values}
final_eda <- final_df %>%
  mutate(
      fatal = case_when(
        fatal == 1 ~ "Fatal",
        fatal == 0 ~ "Non-Fatal"),
      sb = case_when(
        sb == 1 ~ "Black Victim Present",
        sb == 0 ~ "Black Victim Not Present"
      ),
      sw = case_when(
        sw == 1 ~ "White Victim Present",
        sw == 0 ~ "White Victim Not Present"
      ),
      sl = case_when(
        sl == 1 ~ "Latino Victim Present",
        sl == 0 ~ "Latino Victim Not Present"
      ),
      sa = case_when(
        sa == 1 ~ "Asian Victim Present",
        sa == 0 ~ "Asian Victim Not Present"
      ),
      so = case_when(
        so == 1 ~ "Other Victim Present",
        so == 0 ~ "Other Victim Not Present"
      ),
      smale = case_when(
        smale == 1 ~ "Male Victim Present",
        smale == 0 ~ "Male Victim Not Present"
      ),
      sfem = case_when(
        sfem == 1 ~ "Female Victim Present",
        sfem == 0 ~ "Female Victim Not Present"
      ),
      ob = case_when(
        ob == 1 ~ "Black Officer Present",
        ob == 0 ~ "Black Officer Not Present"
      ),
      ow = case_when(
        ow == 1 ~ "White Officer Present",
        ow == 0 ~ "White Officer Not Present"
      ),
      ol = case_when(
        ol == 1 ~ "Latino Officer Present",
        ol == 0 ~ "Latino Officer Not Present"
      ),
      oa = case_when(
        oa == 1 ~ "Asian Officer Present",
        oa == 0 ~ "Asian Officer Not Present"
      ),
      oo = case_when(
        oo == 1 ~ "Other Officer Present",
        oo == 0 ~ "Other Officer Not Present"
      ),
      omale = case_when(
        omale == 1 ~ "Male Officer Present",
        omale == 0 ~ "Male Officer Not Present"
      ),
      weapon_other = case_when(
        weapon_other == 1 ~ "Other Weapon Present",
        weapon_other == 0 ~ "Other Weapon Not Present"
      ), 
      replica = case_when(
        replica == 1 ~ "Replica Present",
        replica == 0 ~ "Replica Not Present"
      ),
      knife = case_when(
        knife == 1 ~ "Knife Present",
        knife == 0 ~ "Knife Not Present"
      ),
      gun = case_when(
        gun == 1 ~ "Gun Present",
        gun == 0 ~ "Gun Not Present"
      ),
      unarmed = case_when(
        unarmed == 1 ~ "Victim Unarmed",
        unarmed == 0 ~ "Victim Armed"
      ),
      unknown_weapon = case_when(
        unknown_weapon == 1 ~ "Weapon Unknown",
        unknown_weapon == 0 ~ "Weapon Known"
      )
  )

saveRDS(final_eda, 'data/final_eda.rds')
```

```{r race shootings vs population demographics}
most_pop <- head(names(sort(table(final_eda$city), decreasing = TRUE)), 4)
i <- 1

for (c in most_pop) {
  temp <- final_eda %>% 
    filter(city == c)
  
  vic <- temp %>% 
  summarise(Black = sum(str_count(SubjectRace, "B")), 
            White = sum(str_count(SubjectRace, "W")),
            Hispanic = sum(str_count(SubjectRace, "L")),
            Asian = sum(str_count(SubjectRace, "A")),
            city_pop_2013 = sum(str_count(SubjectRace, "B")) + sum(str_count(SubjectRace, "W")) + 
              sum(str_count(SubjectRace, "L")) + sum(str_count(SubjectRace, "A")) + 
              sum(str_count(SubjectRace, "O"))
  ) %>% 
    mutate(Black = Black/city_pop_2013, 
           White = White/city_pop_2013,
           Hispanic = Hispanic/city_pop_2013,
           Asian = Asian/city_pop_2013)
  
  vic <- vic %>%
    t() %>%
    as.data.frame(stringsAsFactors = F) %>%
    rownames_to_column("race") %>%
    `rownames<-`(NULL)

  demo <- temp %>% 
    select(black, white, hispanic, asian, city_pop_2013)  %>% 
    mutate(black = black/city_pop_2013, 
           white = white/city_pop_2013,
           hispanic = hispanic/city_pop_2013,
           asian = asian/city_pop_2013)
  demo <- rename(demo, Black = black, White = white, Hispanic = hispanic, Asian = asian)
  demo <- demo[1,]
  
  demo <- demo %>%
    t() %>%
    as.data.frame(stringsAsFactors = F) %>%
    rownames_to_column("race") %>%
    `rownames<-`(NULL)
  demo <- rename(demo, V1 = 2)
  
  temp2 <- merge(vic, demo, by = "race") %>% 
    filter(race != "city_pop_2013")
  temp2 <- rename(temp2, "Shootings" = V1.x, "City-Wide" = V1.y)
  temp2 <- melt(temp2)
  
  if (c == "LosAngeles") {
    c <- "Los Angeles"
  }
  
  plot <- ggplot(temp2, aes(x = race, y = value, fill = variable)) +
    geom_bar(position = "dodge", stat="identity") + 
    labs(x = "Victim Race", y = "Proportion", title = paste0("Race Demographics of Shooting Victims vs. ", c, " Population in 2013")) +
    theme(legend.text = element_text(size = 8),
          legend.key.size = unit(0.4, "cm"),
          plot.title = element_text(size=13, hjust = 0.5)) + 
    scale_fill_manual(values=c("#D48C7D", "#7DB2D4"))
  
  ggsave(filename = paste0("figures/cityeda", i, ".png"), plot)
  
  i <- i + 1
}
```

```{r split into single vs mult}
single_victims <- final_eda %>% 
  filter(NumberOfSubjects <= 1)
nrow(single_victims)

mult_victims <- final_eda %>% 
  filter(NumberOfSubjects > 1)
nrow(mult_victims)
```

```{r single victims race counts and props}
tempsb <- single_victims %>% 
  group_by(sb, fatal) %>% 
  summarise(count = n())
tempsb <- tempsb[3:4,]
tempsb <- rename(tempsb, type = sb)

tempsw <- single_victims %>% 
  group_by(sw, fatal) %>% 
  summarise(count = n())
tempsw <- tempsw[3:4,]
tempsw <- rename(tempsw, type = sw)

tempsa <- single_victims %>% 
  group_by(sa, fatal) %>% 
  summarise(count = n())
tempsa <- tempsa[3:4,]
tempsa <- rename(tempsa, type = sa)

tempsl <- single_victims %>% 
  group_by(sl, fatal) %>% 
  summarise(count = n())
tempsl <- tempsl[3:4,]
tempsl <- rename(tempsl, type = sl)

tempso <- single_victims %>% 
  group_by(so, fatal) %>% 
  summarise(count = n())
tempso <- tempso[3:4,]
tempso <- rename(tempso, type = so)

temp <- rbind(tempsb, tempsw, tempsl, tempsa, tempso) %>% 
  group_by(type) %>% 
  mutate(total = sum(count)) %>% 
  ungroup() %>% 
  mutate(prop = count / total)

race_count <- ggplot(temp, aes(x = type, y = count, fill = fatal)) +
  geom_bar(position = "dodge", stat="identity") + 
  labs(x = "Victim Race", y = "Count", title = "Counts for Fatal vs. Non-Fatal Single-Victim Police Shootings Across Different Races") +
  theme(legend.text = element_text(size = 8),
        legend.key.size = unit(0.4, "cm"),
        axis.text.x = element_text(angle = 10, hjust = 1, size = 8),
        plot.title = element_text(size=10, hjust = 0.5)) + 
  scale_fill_manual(values=c("#D48C7D", "#7DB2D4"))

race_prop <- ggplot(temp, aes(x = type, y = prop, fill = fatal)) +
  geom_bar(position = "stack", stat="identity") + 
  labs(x = "Victim Race", y = "Proportion", title = "Proportions for Fatal vs. Non-Fatal Single-Victim Police Shootings Across Different Races") +
  theme(legend.text = element_text(size = 7),
        legend.key.size = unit(0.4, "cm"),
        axis.text.x = element_text(angle = 10, hjust = 1, size = 8),
        plot.title = element_text(size=10, hjust = 0.5)) + 
  scale_fill_manual(values=c("#D48C7D", "#7DB2D4"))

ggsave(filename = "figures/singleeda1.png", race_count)
ggsave(filename = "figures/singleeda2.png", race_prop)
```

```{r multiple victims race counts and props}
tempsb <- mult_victims %>% 
  group_by(sb, fatal) %>% 
  summarise(count = n())
tempsb <- tempsb[3:4,]
tempsb <- rename(tempsb, type = sb)

tempsw <- mult_victims %>% 
  group_by(sw, fatal) %>% 
  summarise(count = n())
tempsw <- tempsw[3:4,]
tempsw <- rename(tempsw, type = sw)

tempsa <- mult_victims %>% 
  group_by(sa, fatal) %>% 
  summarise(count = n())
tempsa <- tempsa[3,]
tempsa[2,] <- list("Asian Victim Present", "Fatal", 0)
tempsa <- rename(tempsa, type = sa)

tempsl <- mult_victims %>% 
  group_by(sl, fatal) %>% 
  summarise(count = n())
tempsl <- tempsl[3:4,]
tempsl <- rename(tempsl, type = sl)

temp <- rbind(tempsb, tempsw, tempsl, tempsa) %>% 
  group_by(type) %>% 
  mutate(total = sum(count)) %>% 
  ungroup() %>% 
  mutate(prop = count / total)

race_count1 <- ggplot(temp, aes(x = type, y = count, fill = fatal)) +
  geom_bar(position = "dodge", stat="identity") + 
  labs(x = "Victim Race", y = "Count", title = "Counts for Fatal vs. Non-Fatal Multiple-Victim Police Shootings Across Different Races") +
  theme(legend.text = element_text(size = 8),
        legend.key.size = unit(0.4, "cm"),
        axis.text.x = element_text(size = 8),
        plot.title = element_text(size=10, hjust = 0.5)) + 
  scale_fill_manual(values=c("#D48C7D", "#7DB2D4"))

race_prop1 <- ggplot(temp, aes(x = type, y = prop, fill = fatal)) +
  geom_bar(position = "stack", stat="identity") + 
  labs(x = "Victim Race", y = "Proportion", title = "Proportions for Fatal vs. Non-Fatal Multiple-Victim Police Shootings Across Different Races") +
  theme(legend.text = element_text(size = 7),
        legend.key.size = unit(0.4, "cm"),
        axis.text.x = element_text(size = 8),
        plot.title = element_text(size=10, hjust = 0.5)) + 
  scale_fill_manual(values=c("#D48C7D", "#7DB2D4"))

ggsave(filename = "figures/multeda1.png", race_count1)
ggsave(filename = "figures/multeda2.png", race_prop1)
```

```{r fatally shot prop for all shootings of varying numbers of victims}
temp <- final_eda %>% 
  group_by(NumberOfSubjects) %>% 
  summarise(prop = sum(fatal == "Fatal")/n(),
            total = n())
temp
```
For sample size > 10, fatality seems to be lower for multiple victims rather than just 1.

```{r black to white ratio}
temp <- final_df %>% 
  group_by(city) %>% 
  summarise(btw = black/white, propfatal = sum(fatal)/n()) %>% 
  unique

plot <- ggplot(temp, aes(x = btw, y = propfatal)) + 
    geom_point()  + 
  labs(x = "Black to White Ratio", y = "Fatal Shootings Proportions", title = "Proportion of Fatal Shootings vs. Black to White Ratios in Cities") +
  theme(legend.text = element_text(size = 8),
        legend.key.size = unit(0.4, "cm"),
        axis.text.x = element_text(angle = 10, hjust = 1, size = 8),
        plot.title = element_text(size=10, hjust = 0.5))

ggsave(filename = "figures/btweda.png", plot)
```

Can't really tell if there's a distribution here, maybe negatively correlated.

```{r black percent}
temp <- final_df %>% 
  group_by(city) %>% 
  summarise(bprop = black/city_pop_2013, propfatal = sum(fatal)/n()) %>% 
  unique

plot <- ggplot(temp, aes(x = bprop, y = propfatal)) + 
    geom_point()  + 
  labs(x = "Black Percentage of Population", y = "Fatal Shootings Proportions", title = "Proportion of Fatal Shootings vs. Black Population Percentages in Cities") +
  theme(legend.text = element_text(size = 8),
        legend.key.size = unit(0.4, "cm"),
        axis.text.x = element_text(angle = 10, hjust = 1, size = 8),
        plot.title = element_text(size=10, hjust = 0.5))

ggsave(filename = "figures/bpropeda.png", plot)
```

Same thing, can't really tell if there's a distribution here, maybe negatively correlated.

```{r}
temp <- final_df %>% 
  summarise(Black = sum(str_count(OfficerRace, "B")), 
            White = sum(str_count(OfficerRace, "W")),
            Hispanic = sum(str_count(OfficerRace, "L")),
            Asian = sum(str_count(OfficerRace, "A")), 
            Other = sum(str_count(OfficerRace, "O")))

temp2 <- temp %>%
    t() %>%
    as.data.frame(stringsAsFactors = F) %>%
    rownames_to_column("race") %>%
    `rownames<-`(NULL)
temp2 <- rename(temp2, Count = 2) %>% 
  mutate(total = Count/sum(Count))

officerplot2 <- ggplot(temp2, aes(x=race, y = total)) +
  geom_bar(position = "dodge", stat="identity", fill ="#D48C7D") + 
  labs(x = "Officer Race", y = "Proportion", title = "Race Proportions of Officers for All Shootings") +
  theme(legend.text = element_text(size = 7),
        legend.key.size = unit(0.4, "cm"),
        plot.title = element_text(size=10, hjust = 0.5))
ggsave(filename = "figures/officerprop.png", officerplot2)
```

```{r sb-officer}
temp <- final_df %>% 
  filter(sb == 1) %>% 
  group_by(fatal) %>% 
  summarise(ob = sum(ob == 1),
            ow = sum(ow == 1),
            ol = sum(ol == 1),
            oa = sum(oa == 1),
            oo = sum(oo == 1)) %>% 
  mutate(ob = ob/(ob + ow + ol + oa + oo), 
         ow = ow/(ob + ow + ol + oa + oo),
         ol = ol/(ol + ow + ol + oa + oo), 
         oa = oa/(ob + ow + ol + oa + oo), 
         oo = oo/(ob + ow + ol + oa + oo))
temp <- rename(temp, Black = ob, White = ow, Latino = ol, Asian = oa, Other = oo)

temp2 <- temp %>%
    t() %>%
    as.data.frame(stringsAsFactors = F) %>%
    rownames_to_column("race") %>%
    `rownames<-`(NULL)
temp2 <- rename(temp2, "Non-Fatal" = 2, Fatal = 3)
temp2 <- temp2[-1,]
temp2 <- melt(temp2)

officerplot <- ggplot(temp2, aes(x=race, y = value, fill = variable)) +
  geom_bar(position = "dodge", stat="identity") + 
  labs(x = "Officer Race", y = "Proportion", title = "Race Proportions of Officers Present at Fatal vs. Non-Fatal Police Shootings Involving Black Victims") +
  theme(legend.text = element_text(size = 7),
        legend.key.size = unit(0.4, "cm"),
        plot.title = element_text(size=10, hjust = 0.5)) + 
  scale_fill_manual(values=c("#D48C7D", "#7DB2D4"))

ggsave(filename = "figures/officerpropsb.png", officerplot)
```

Nothing too crazy happening here. 