---
title: "Modeling"
author: "Connie Wu"
date: "10/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Modeling
```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(tidyverse)
```

```{r load-data}
# Shootings
all <- read.csv("data/allshootingsdata.csv")
all <- all %>% 
  mutate(id = paste0("C", row_number()))

# Census Predictors
census <- read.csv("data/2013census.csv")[,-c(8,9)]
states <- lapply(census$department, function(x) str_extract_all(x,"\\([^()]+\\)")[[1]])
states <- substring(states, 2, nchar(states)-1)
census$state <- states

# Gun Law Predictors
gun_provisions <- read.csv("data/gun_provisions.csv") %>% 
  filter(year == 2013)
gun_provisions <- gun_provisions %>% 
  mutate(total_pr = rowSums(gun_provisions[,3:136]),
         deesc_train = ifelse(state %in% c("California", "New Mexico", "Texas", "Oklahoma", "South Dakota", "Illinois", "Indiana", "Tennessee", "Washington", "Missouri", "Georgia", "Ohio", "Maryland", "Massachusetts", "Connecticut", "Maine"), 1, 0)) %>% 
  select(state, total_pr, deesc_train)
gun_provisions$state <- state.abb[match(gun_provisions$state,state.name)]
```

```{r clean-all}
all <- all %>% 
  select(-c("Date", "NatureOfStop", "Notes", "SubjectAge", "NumberOfShots", "Department", "FullNarrative", "fdate", "month", "day", "tr", "AvgAge", "VA", "F", "nshots", "sit"))

all <- all %>% 
  separate_rows(SubjectRace, SubjectGender, Fatal, sep = ";")

officer_gender <- sapply(str_split(all$OfficerGender, ";"), length)
officer_race <- sapply(str_split(all$OfficerRace, ";"), length)
out <- which((officer_gender == officer_race) == FALSE)
all <- all[-out,]

all <- all %>% 
  separate_rows(OfficerRace, OfficerGender, sep = ";") %>% 
  separate_rows(OfficerRace, OfficerGender, sep = ",") 

officer_gender2 <- sapply(str_split(all$OfficerGender, "/"), length)
officer_race2 <- sapply(str_split(all$OfficerRace, "/"), length)
out2 <- which((officer_gender2 == officer_race2) == FALSE)
all <- all[-out2,]

all$OfficerRace <- trimws(all$OfficerRace)
all$OfficerGender <- trimws(all$OfficerGender)
all$Fatal <- trimws(all$Fatal)

all <- all %>% 
  filter(SubjectRace != "U") %>% 
  filter(OfficerRace != "U") %>% 
  filter(OfficerRace != "Unknown") %>% 
  filter(OfficerRace != "NA") %>% 
  filter(OfficerRace != "") %>% 
  filter(OfficerRace != "I") %>% 
  filter(OfficerGender != "U") %>% 
  filter(OfficerGender != "N") %>% 
  filter(SubjectGender != "U") %>% 
  filter(SubjectGender != "N") %>% 
  filter(Fatal != "U")

all$OfficerRace[all$OfficerRace == "WHITE"] <- "W"
all$OfficerRace[all$OfficerRace == "BLACK"] <- "B"
all$OfficerRace[all$OfficerRace == "ASIAN"] <- "A"

all$OfficerGender[all$OfficerGender == "FEMALE"] <- "F"
all$OfficerGender[all$OfficerGender == "MALE"] <- "M"
all$OfficerGender[all$OfficerGender == "Male"] <- "M"
```